
name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      # Use the capxmock server to fake an api response
      CAPX_URL: http://capx_mock:3030
      CAPX_API_KEY: dummy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test image builds
        run: |
          docker compose -f compose.yml build

      - name: Test container can start and is healthy
        run: |          
          # Launch the project from docker-compose.yml and wait up to
          # 30s for its built-in health check to return "healthy"
          docker compose -f compose.yml -f compose.test.yml up --wait --wait-timeout 30
          docker compose -f compose.yml run --entrypoint "" web pytest
          docker compose -f compose.yml down
